name: Maven Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java_version: [11, 13]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: ${{ matrix.java_version}}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
